<?php
    $this->headScript()->appendFile($this->basePath('Core/js/notification.js'));
    $messenger = $this->flashMessenger();
    $alert     = $this->plugin('alert');
    $translate = $this->plugin('translate');
?>

<div class="ppt-notifications">
<?php foreach (array('danger', 'warning', 'success', 'info') as $ns):
    $messages = array_merge(
        $messenger->getMessagesFromNamespace($ns),
        $messenger->getCurrentMessagesFromNamespace($ns)
    );

    $messenger->clearCurrentMessagesFromNamespace($ns);
    
    foreach ($messages as $message):
        echo $alert->render($ns, $translate($message));
    endforeach;
endforeach ?>        
</div>
