<?php if ($this->pageCount): 
    $query = $this->params()->fromQuery();
?>
    <div class="row ppt-pagination">
    <div class="col-xs-6">
    <!-- First page link -->
    <ul class="pagination">
    <?php if (isset($this->previous)): ?>
      <li><a title="<?php echo  $this->translate('First')?>" href="<?php $query['page'] = $this->first; echo $this->url($this->route, array('lang' => $this->lang), array('query'=>$query), true); ?>">
        <i class="ppt-icon ppt-icon-pagination-start"></i>
      </a></li>
    <?php else: ?>
      <li class="disabled"><a title="<?php echo $this->translate('First');?>"><i class="ppt-icon ppt-icon-pagination-start"></i></a></li>
    <?php endif; ?>
    <!-- Previous page link -->
    <?php if (isset($this->previous)): ?>
      <li><a href="<?php $query['page'] = $this->previous; echo $this->url($this->route, array('lang' => $this->lang), array('query'=>$query), true); ?>">
        <?php echo  $this->translate('&lt; Previous')?>
      </a></li>
    <?php else: ?>
      <li class="disabled"><a><?php echo  $this->translate('&lt; Previous')?></a></li>
    <?php endif; ?>
    <!-- Next page link -->
    <?php if (isset($this->next)): $query['page'] = $this->next; ?>
      <li><a href="<?php echo $this->url($this->route, array('lang' => $this->lang), array('query'=>$query), true); ?>">
        <?php echo  $this->translate('Next &gt;')?>
      </a></li>
    <?php else: ?>
      <li class="disabled"><a>Next &gt;</a></li>
    <?php endif; ?>
    <!-- Last page link -->
    <?php if (isset($this->next)): $query['page'] = $this->last; ?>
      <li><a title="<?php echo  $this->translate('Last')?>" href="<?php echo $this->url($this->route, array('lang' => $this->lang), array('query'=>$query), true); ?>">
        <i class="ppt-icon ppt-icon-pagination-end"></i>
      </a></li>
    <?php else: ?>
      <li class="disabled"><a title="<?php echo  $this->translate('Last')?>"><i class="ppt-icon ppt-icon-pagination-end"></i></a></li>
    <?php endif; ?>
    </ul>
    </div>
    <div class="col-xs-6 text-right">
    <?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
     of <?php echo $this->totalItemCount; ?>
    </div>
    <i class="ppt-icon ppt-icon-spinner fa-spin pagination-loading"></i> 
    </div>
<?php endif; ?>
