<?php 
use Applications\Entity\StatusInterface as Status;
      
$this->headTitle($this->translate('Details'));
$this->headScript()->appendFile($this->basePath('Applications/js/applications.manage.detail.js'));
$this->headScript()->appendScript('$(function() { $(".rating").barrating(); });');

/* variables needed for the pagination*/
$prevId = $this->list->getPrevious();
$nextId = $this->list->getNext();
$prevHref = $prevId ? $this->url('lang/applications/detail', array('id' => $prevId), true) : '#';
$nextHref = $nextId ? $this->url('lang/applications/detail', array('id' => $nextId), true) : '#';
            
?>
<h1>
<?php echo $this->translate('Application for')?> 
<small><?php echo $this->link($this->application->job->link, $this->application->job->title)?></small>
<small class="pull-right">
    <?php echo sprintf($this->translate('Application %d of %d'),
                       $this->list->getPosition(), $this->list->getCount()
                )?>
</small>
</h1>

<div id="forward-email-result" class="alert" style="display:none"></div>

<nav class="navbar ats-toolbar">  
    <div class="col-xs-12 row">
<!--    <form id="forward-email-form" action="<?php echo $this->url('lang/applications/detail',array(), true)?>" method="get">
      <div id="forward-email" class="ats-input-group input-group">
             <span class="input-group-addon"
             data-toggle="popover" 
             data-trigger="hover focus click"
             data-placement="bottom" 
             title="<?php echo $this->translate('Enter an email address')?>"
             data-content="<?php echo $this->translate('This application will be send as an email to the given address in a layout similar to that on this page with all attachments included.')?>">
             <i class="ppt-icon ppt-icon-envelope"></i>
             </span>
             <input type="hidden" name="action" value="forward">
             <input class="form-control" id="forward-email-input" name="email" type="email">
             <span class="input-group-btn">
             <button class="btn btn-default" type="submit">
              <span class="ppt-icon ppt-icon-forward"></span> <?php echo $this->translate('Forward')?>
             </button>
             </span>
       </div>
     </form>-->
    <div class="btn-group pull-right">
       <a href="<?php echo $prevHref ?>" class="btn btn-mini btn-default<?php if (!$prevId): echo " disabled"; endif; ?>" title="<?php echo $this->translate('previous')?>"><span class="ppt-icon fa-chevron-left"></span></a>
       <a href="<?php echo $this->url('lang/applications', array(), true) ?>" class="btn btn-mini btn-default" title="<?php echo $this->translate('Back to list') ?>"><span class=""></span> <?php echo $this->translate('List') ?></a>
       <a href="<?php echo $nextHref ?>" class="btn btn-mini btn-default<?php if (!$nextId): echo " disabled"; endif; ?>" title="<?php echo $this->translate('next')?>"><span class="ppt-icon fa-chevron-right"></span></a>
     </div>   
    </div>
    <hr />
    <div class="col-xs-12 row">

    </div>
</nav>

<div id="mail-box" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mail-box-label" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="mail-box-label">
            <?php echo $this->translate('Process the applicant') ?>
          </h3>
      </div>
        <div id="mail-box-content" class="modal-body"></div>
        <div class="modal-footer">
          <button class="btn btn-default" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('Cancel') ?></button>
          <button class="btn btn-primary" onclick="$('#applicant-mail').submit()"><?php echo $this->translate('Continue') ?></button>
        </div>
     </div>
  </div>
</div>
<div id="ats-delete-application" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="delete-application-label" aria-hidden="true">
  <div class="modal-dialog">
   <div class="modal-content">
     <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="delete-application-label">
          <?php echo $this->translate('Delete Application') ?>:
        </h3>
      </div>
      <div class="modal-body">
      <?php echo $this->translate('Are you sure you want to delete this application?')?>
      </div>
      <div class="modal-footer">
          <button class="btn btn-default" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('Cancel') ?></button>
          <a class="btn btn-primary" href="<?php echo $this->url('lang/applications/detail', array('id' => $application->id), array('query' => 'action=delete'), true)?>" title="<?php echo $this->translate('delete this application')?>">
          <?php echo $this->translate('Delete application') ?></a>
      </div>
    </div>
  </div>
</div>

<div id="ats-application-comments" class="modal fade modal-scrollable" tabindex="-1" role="dialog" aria-hidden="true"
     data-list-errormessage="<?php echo $this->translate('Error while loading comments.')?>"
     data-list-url="<?php echo $this->url(
                        'lang/applications/comments', array('action' => 'list'), 
                        array('query' => array(
                            'applicationId' => $this->application->id
                        )), true
                    )?>"
     data-form-errormessage="<?php echo $this->translate('Error while loading comment form.')?>"
     data-form-url="<?php echo $this->url(
                        'lang/applications/comments', array('action' => 'form'),
                         true)?>"
     data-application-id="<?php echo $this->application->id ?>"
     data-mode="list"
>
  <div class="modal-dialog">
   <div class="modal-content">
     <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3><?php echo $this->translate('Comments') ?> <i class="ppt-icon ppt-icon-spinner fa-spin"></i> </h3>
     </div>
     <div id="ats-application-comments-body" class="modal-body">
        <div class="ats-error hide"><p></p></div>
     </div>
     <div class="modal-footer">
         <button id="ats-application-comments-cancelbtn" class="btn btn-default hide"><?php echo $this->translate('Cancel') ?></button>
         <button id="ats-application-comments-savebtn" class="btn btn-primary hide"><?php echo $this->translate('Save') ?></button>
         <button id="ats-application-comments-addbtn" class="btn btn-primary" ><?php echo $this->translate('Add new comment') ?></button>
         <button id="ats-application-comments-closebtn" class="btn btn-default" data-dismiss="modal" aria-hidden="true"><?php echo $this->translate('Close') ?></button>
     </div>
   </div>
 </div>
</div>

<div id="ats-application-history" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="history-box-label" aria-hidden="true">
  <div class="modal-dialog">
   <div class="modal-content">
     <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="history-box-label">
          <?php echo $this->translate('State history') ?>:
        </h3>
      </div>
      <div class="modal-body">
        <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th><?php echo $this->translate('Date') ?></th>
                <th><?php echo $this->translate('State') ?></th>
                <th><?php echo $this->translate('Comment') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->application->history as $history): ?>
            <tr>
                <td><?php echo $this->dateFormat($history->date)?></td>
                <td><span class="ats-application-status <?php echo $history->status ?>"><?php echo $this->translate($history->status) ?></span></td>
                <td><?php echo $history->message ?></td>
            </tr>
            <?php endforeach ?>
        </tbody>
        </table>     
      </div>
    </div>
  </div>
</div>

<div class="row">
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading"><?php echo $this->translate('Personal Information') ?></div>
            <div class="panel-body">
                <div class="col-xs-6">
                    <div class="row">
                    <p>
                        <?php if (count($this->application->user->cv->educations)>0):?>
                              <?php echo $this->translate('Education').': <span class="badge">'.$this->period($this->application->user->cv->educations).' '.$this->translate('years'). '</span>' ?>
                          <?php endif;?>
                          <?php if (count($this->application->user->cv->employments)>0):?>
                              <?php echo $this->translate('Work Experience').': <span class="badge">'.$this->period($this->application->user->cv->employments).' '.$this->translate('years'). '</span>' ?>
                          <?php endif;?>  
                      </p>
                    </div>
                    <div class="row">
                        <div class="col-xs-4">
                            <div class="ppt-portrait text-center quiet">
                                <?php if ($this->application->user->info->image): ?>
                                    <img src="<?php echo $this->basePath($this->application->user->info->image->uri) ?>" class="img-thumbnail"/>
                                <?php else: ?>
                                    <span class="ppt-icon ppt-icon-portrait fa-fg img-thumbnail text-center quiet"></span>
                                <?php endif ?>
                            </div>  
                            <div class="clearfix"></div>
                            <?php if (! $this->acl()->isRole('user')):?> 
                                <p>
                                    <br />
                                    <a class="btn btn-default" href="<?php echo $this->url('lang/cvs/edit', array('id' => $this->application->user->cv->id), true) ?>"
                                              title="<?php echo $this->translate('Edit Information')?>"> 
                                      <i class="ppt-icon ppt-icon-edit"></i> <?php echo $this->translate('Edit Information')?>
                                    </a>
                                </p>
                            <?php endif ?>   
                        </div>

                        <adress>
                            <strong><?php echo $this->application->user->info->displayName ?></strong><br> 
                            <?php echo $this->application->user->info->street ?> <?php echo $this->application->user->info->houseNumber ?><br>
                            <?php echo $this->application->user->info->postalcode ?> <?php echo $this->application->user->info->city ?><br>
                            <br>
                            <?php if ($this->application->user->info->phone): ?>
                                <i class="ppt-icon ppt-icon-phone"></i> <?php echo $this->application->user->info->phone; ?><br>
                            <?php endif ?>
                            <?php if ($this->application->user->info->email): ?>
                                <i class="ppt-icon ppt-icon-envelope"></i> <?php echo $this->link($this->application->user->info->email); ?><br>
                            <?php endif ?>
                        </adress>
                </div>
                </div>
                <div class="col-xs-6">
                <div class="jumbotron text-center" style="margin-bottom: 0">
                    <p class="ats-application-status <?php echo $this->application->status ?>"><?php echo $this->translate((string) $this->application->status) ?></p>
                    <p>
                        <?php if (isset($externActionButtons)) {
                         echo $externActionButtons;
                        } ?>
                        <?php if ($this->acl($this->application, 'delete') || $this->acl()->isRole('admin')):?>            
                        <button class="btn btn-default" data-title="delete Application"
                                  data-toggle="modal"
                                  data-target="#ats-delete-application"
                                  title="<?php echo $this->translate('Delete application')?>"> 
                          <i class="ppt-icon ppt-icon-delete"></i> <?php echo $this->translate('Delete Application')?>
                        </button>
                        <?php endif ?>                        
                    </p>
                    <p>
                    <?php if ($this->application->getPermissions()->isGranted($this->auth('id'), 'change') || $this->acl()->isRole('admin')): ?>

                        <div id="state-actions" class="btn-group ats-action-states">
                            <?php $status = $application->status->name;

                                $actionButtons = array(
                                    Status::PROCESS => array(
                                        'href' => $this->url(
                                                    'lang/applications/detail/status',
                                                    array('status' => Status::PROCESS),
                                                    true
                                                  ),
                                        'label' => $this->translate('Process'),
                                        'title' => $this->translate('Process the applicant'),
                                    ),
                                   
                                    Status::FAILED => array(
                                        'href' => $this->url(
                                                    'lang/applications/detail/status',
                                                    array('status' => Status::FAILED),
                                                    true
                                                  ),
                                        'label' => $this->translate('Fail'),
                                        'title' => $this->translate('Fail the applicant'),
                                    ),
                                    Status::HIRED => array(
                                        'href' => $this->url(
                                                    'lang/applications/detail/status',
                                                    array('status' => Status::HIRED),
                                                    true
                                                  ),
                                        'label' => $this->translate('Hired'),
                                        'title' => $this->translate('Mark as Hired'),
                                    ),                                     

                                );

                                foreach ($actionButtons as $targetStatus => $spec):
                                    if ($status == $targetStatus): continue; endif?>

                                <button class="btn btn-default btn-large" 
                                        data-href="<?php echo $spec['href']?>"
                                        <?php if (isset($spec['title'])):?>
                                        data-title="<?php echo $spec['title']?>"
                                        data-toggle="modal"
                                        data-target="#mail-box"
                                        <?php endif ?>
                                ><?php echo $spec['label'] ?></button>
                                <?php endforeach ?>  
                         </div>
                     <?php endif ?>    
                </p>
                </div>
            </div>
        </div>
    </div>

<div class="row">      
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading"><?php echo $this->translate('State') ?></div>
            <table class="table">
                <tbody>
                    <tr>
                        <td  style="width:20%"><?php echo $this->translate('Date of Receipt') ?>:</td>
                        <td><?php echo strftime('%x %X', $application->dateCreated->getTimestamp()); ?></td>
                    </tr> 
                    <tr>
                        <td><?php echo $this->translate('Rating and Comments') ?>:</td> 
                        <td class="col-xs-6">
                            <span id="application-rating">
                                <button id="<?php echo $this->application->rating ? "ats-applications-comments-toggle" : "ats-applications-comments-quickadd" ?>" 
                                        data-title="title"
                                        <?php echo $this->application->rating ? 'data-toggle="modal"' : '' ?>
                                            <?php echo $this->application->rating ? 'data-target="#ats-application-comments"' : '' ?> 
                                        title="<?php echo $this->application->rating ? $this->translate('View comments') : $this->translate('Add comment') ?>">
                                <?php echo $this->partial('applications/manage/_rating', array('application' => $this->application)) ?>
                                </button>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td><?php echo $this->translate('Agent') ?>:</td>
                        <td><?php echo $this->application->job->contactEmail ?></td>
                    </tr>                    
                    <?php if ($application->dateCreated->getTimestamp() != $application->dateModified->getTimestamp()): ?>
                    <?php 
                        $history = $this->application->history->toArray();
                        $latest = end($history);
                        if($latest): ?>
                        <tr>
                            <td>
                                <?php echo $this->translate('Last State') ?>:
                            </td>
                            <td>
                                    <span class="ats-application-status-text <?php echo $latest->status ?>">
                                        <?php echo $latest->status ?>
                                    </span>
                                    <small class="muted">
                                        <?php echo $this->translate('on') ?> <?php echo $this->dateFormat($application->dateModified->getTimestamp()); ?>
                                    </small> :
                                    <?php echo $latest->message ?>
                                <?php if(count($history) > 1): ?>
                                    <a data-title="title"
                                       data-toggle="modal"
                                       class="btn btn-link btn-xs"
                                       data-target="#ats-application-history"
                                       title="<?php echo $this->translate('See All History') ?>">
                                        <i class="fa fa-eye"></i> <?php echo $this->translate('See All History') ?>
                                    </a>
                                <?php endif; ?>
                            </td>
                        </tr>
                        <?php endif; ?>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<?php echo $this->partial('cv/manage/detail', array('cv' => $this->application->user->cv)) ?>

<div class="row">
    <div class="col-xs-12">
           <div class="panel panel-default">
               <div class="panel-heading"><?php echo $this->translate('Summary') ?></div>       
               <div class="panel-body">
                    <?php echo trim($this->application->user->cv->summary) ? nl2br($this->application->user->cv->summary) : '-'; ?>
               </div>
           </div>
    </div>
</div>
<!--        
<div class="row">        
    <div class="col-xs-12">
        <div class="panel panel-default">
            <div class="panel-heading"><?php //echo $this->translate('Attachments') ?></div> 
            <div class="panel-body">
                <?php //if (count($this->application->attachments) > 0): ?>
                    <?php //foreach ($this->application->attachments as $attachment): ?>
                        <div class="row show-grid">
                            <div class="col-xs-12">
                                <span class="ppt-icon ppt-icon-paperclip"></span> <a href="<?php //echo $this->basePath($attachment->uri) ?>" target="_new"><?php //echo $attachment->name ?></a>
                            </div>
                        </div>
                    <?php //endforeach; // attachments?>
                <?php //else: ?>
                    -
                <?php //endif; ?>
                <?php //if (count($this->application->profiles)): ?>
                    <hr>
                    <?php //foreach ($this->application->profiles as $profile): ?>

                        <a data-toggle="modal" data-target="#sp-modal" class="btn-sp btn btn-default" href="?action=social-profile&spId=<?php //echo $profile->id ?>">
                            <span class="fa fa-<?php //echo strtolower($profile->name) ?>"></span>
                            <?php //echo $profile->name ?>
                        </a>

                    <?php //endforeach;
                        //$this->headScript()->appendFile($this->basePath('Core/js/jquery.reloadable-modal.js'))
                    ?>
                    <div class="modal fade modal-scrollable" id="sp-modal" data-reloadable="body" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                    <h4 class="modal-title">
                                        <span class="fa-spin ppt-icon ppt-icon-spinner"></span>
                                    <?php //echo $this->translate('Loading') ?> ...</h4>
                                </div>
                                <div class="modal-body">

                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-primary" data-dismiss="modal"><?php //echo $this->translate('Close') ?></button>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php //endif; ?>
            </div>
        </div>
    </div>
</div>-->