<?php
$formCheckBox = $this->services("FormElementManager.checkBox");
$formCheckBox->setAttributes(array('name' => 'unused', 'style' => 'margin-top:-4px'));

$columns = array(
    /* @translate */ 'Details' => array(),
    /* @translate */ 'Position Applied' => array('class' => 'ppt-job', 'class' => 'col-xs-2'),
    /* @translate */ 'Status' => array('sort' => 'status'),
//    /* @translate */ 'Rating' => array('sort' => 'rating'),
//    /* @translate */ 'Modified' => array('sort' => 'date'),
    /* @translate */ 'Actions' => array(),
);

if ('-' == $this->sort{0}) {
    $sortBy = substr($this->sort, 1);
    $sortDir = false;
} else {
    $sortBy = $this->sort;
    $sortDir = true;
}
?>
<?php if (!$this->isAjaxRequest): ?>
<div class="panel panel-default pagination-container">
<?php endif ?>
<div class="panel-heading">
<?php echo $this->translate('List of applications') ?>
</div>
<table class="table table-striped table-hover" id="ats-application-lists">
    <thead>
        <tr>
            <th class="col-xs-1">
                <?php echo $this->formCheckBox($formCheckBox); ?>
                
                <span class="dropdown" id="action">
                   
                    <a class="btn btn-xs dropdown-toggle table-action" data-toggle="dropdown" style="margin-top: -8px;">
                        <i class="fa fa-ellipsis-h"></i> 
                        <i class="fa fa-chevron-down"></i> 
                        <i class="ppt-icon ppt-icon-spinner fa-spin action-loading" style="display: none;"></i>
                    </a>
                    <ul id="applicationTableAction" class="dropdown-menu">
                        <li>
                        <li>
                            <a href="#FailApplication"><?php echo $this->translate('Fail') ?></a>
                        </li>
                    </ul>
                </span>  
            </th>
            <?php foreach ($columns as $label => $option): ?>

                <th <?php echo isset($option['class']) ? 'class="' . $option['class'] . '"' : ''; ?>>
                    <?php
                    if (!isset($option['sort'])): echo $this->translate($label);
                    else:
                        if ($option['sort'] == $sortBy):
                            $icon = '<span class="pull-right text-right ppt-icon ppt-icon-sort' . ($sortDir ? '-desc' : '-asc') . '"></span>';
                            $dir = !$sortDir;
                        else:
                            $dir = true;
                            $icon = '<span class="pull-right ppt-icon ppt-icon-sort"></span>';
                        endif;
                        $sortParam = array('sort' => ($dir ? '' : '-') . $option['sort']);
                        $url = $this->url(
                                'lang/applications', array(), array('query' => array_merge($this->params()->fromQuery(), $sortParam)), true
                        );
                        ?>
                        <a href="<?php echo $url ?>"><?php echo $this->translate($label) . $icon ?></a>     
                    <?php endif; ?>
                </th>
            <?php endforeach; ?>
        </tr>
    </thead>

    <tbody>
        <?php
        foreach ($this->applications as $application):
            $isUnread = $application->isUnreadBy($this->auth('id'));
            ?>
            <tr<?php echo ($isUnread ? ' class="ppt-new"' : "") ?>>
                <td>
                    <?php
                    $formCheckBox = $this->services("FormElementManager.checkBox");
                    $formCheckBox->setAttributes(array('id' => $application->id, 'name' => 'cb_' . $application->id));
                    echo $this->formCheckBox($formCheckBox);
                    ?>
                </td>      
                <td>
                    <div class="portrait">
                        <?php if ($application->user->info->image): ?>
                            <img src="<?php echo $this->basePath($application->user->info->image->uri) ?>" />
                        <?php else: ?>
                            <span class="ppt-icon ppt-icon-portrait fa-3x text-center quiet"></span>
                        <?php endif ?>
                    </div>
                    <div class='pull-left'>
                        <h2 class="table-data-title">
                            <?php echo $this->translate($this->salutation($application->user->info->gender)) ?>
                            <?php echo $application->user->info->displayName ?>
                        </h2>
                        <?php echo $application->user->info->city ?>
                        <div class='clearfix'></div>
                        <?php if (isset($application->user->cv) && count($application->user->cv->educations) > 0): ?>
                            <?php echo $this->translate('Education') . ': ' . $this->period($application->user->cv->educations) . ' ' . $this->translate('years') ?><br/>
                        <?php endif; ?>
                        <?php if (isset($application->user->cv) && count($application->user->cv->employments) > 0): ?>
                            <?php echo $this->translate('Work Experience') . ': ' . $this->period($application->user->cv->employments) . ' ' . $this->translate('years') ?><br/>
                        <?php endif; ?>
                        <?php //if (count($application->attachments) > 0): ?>
                            <!--<ul class="media-list">-->
                                <?php //foreach ($application->attachments as $attachment): ?>
                                    <!--<li class="media">-->
                                        <!--<i class="ppt-icon ppt-icon-paperclip pull-left"></i>-->
                                        <!--<div class="media-body">-->
                                            <!--<a href="<?php //echo $this->basePath($attachment->uri) ?>">-->
                                                <?php //echo $attachment->name ?>
                                            <!--</a>-->
                                        <!--</div>-->
                                    <!--</li>-->
                                <?php //endforeach; ?>
                            <!--</ul>-->
                        <?php //else: ?>
                            <?php //echo $this->translate('No attachment'); ?>
                        <?php //endif; ?>
                    </div>
                </td>
                <td class="ats-job">
                    <a href="<?php echo $this->url('lang/applications/detail', array('id' => $application->id), /* reuse matched params */ true) ?>">
                        <?php echo strip_tags($application->job->title) ?>
                    </a>         
                </td>
                <td>
                    <span class="ats-application-status <?php echo $application->status->name ?>"><?php echo $this->translate($application->status->name) ?></span>
                    <?php echo isset($application->subscriber) ? $application->subscriber->name : '' ?>
                </td>
                <!--<td><?php // echo $this->rating($application->rating) ?></td>-->
<!--                <td title="Created: <?php echo $this->dateFormat($application->dateCreated, 'short'); ?>">
                    <?php echo $this->dateFormat($application->dateModified); ?>
                </td>-->
                <td>
                    <div class="btn-group">
                        <a href="<?php echo $this->url('lang/applications/detail', array('id' => $application->id), true) ?>" class="btn btn-xs btn-default pull-right" title="<?php echo $this->translate('Details') ?>"><span class="ppt-icon ppt-icon-folder-open-o"></span></a>
                    </div>
                </td>
            </tr>

        <?php endforeach ?>
    </tbody>
</table>
<div class="ats-panel-foot">
<?php echo $this->paginationControl($this->applications, 'Sliding', 'pagination-control', array('lang' => $this->params('lang'), 'route' => 'lang/applications')); ?>
</div>
<?php if (!$this->isAjaxRequest): ?>
</div>
<?php endif ?>