<?php

$this->headScript()->appendFile($this->basePath('Core/js/core.pagination.js'));
?>
<?php if (!$this->isAjaxRequest): ?>
<div class="panel panel-default pagination-container">
<?php endif ?>
<div class="panel-heading">
 <!--<a style="text-decoration: none;" href="<?php echo $this->url('lang/applications', array(), array('query' => ""), true)?>">-->
  <?php echo $this->translate('Current Applications')?>
 <!--</a>-->
 <small>
 <?php #if ($hasJobs): ?>
 <?php 
      #$countTmpl = '<span style="font-size:16px; font-weight:bold;">%s</span>';
      #$newCount = $appRepo->countBy($this->auth('id'), /* unread */ true);
      #$totalCount = $appRepo->countBy($this->auth('id'));
      #echo sprintf($this->translate('%1$s new from %2$s total applications'),
      #             sprintf('<span class="badge">'.$countTmpl.'</span>', $newCount), 
      #             sprintf('<span class="badge">'.$countTmpl.'</span>', $totalCount))?>
 <?php #endif ?>
 </small>
 <i class="pagination-loading ppt-icon ppt-icon-spinner pull-right"></i>
</div>
<table class="table table-striped table-hover" id="ats-application-list">
<thead>
 <tr>
  <th><?php echo $this->translate('Applicant')?></th>
  <th><?php echo $this->translate('Job')?></th>
  <th><?php echo $this->translate('Status')?></th>
  <th><?php echo $this->translate('Date')?></th>
 </tr>
</thead>
<?php foreach ($this->applications as $app):?>
    <tr>
      <td>
        <div class="portrait">
          <?php if ($app->user->info->image):?>
            <img src="<?php echo $this->basePath($app->user->info->image->uri) ?>" />
          <?php else:?>
            <span class="ppt-icon ppt-icon-portrait fa-3x text-center quiet"></span>
          <?php endif?>
        </div>
        <a href="<?php echo $this->url('lang/applications/detail', array('id' => $app->id), true)?>">
          <?php echo $this->translate($this->salutation($app->user->info->gender))?>
          <?php echo $app->user->info->displayName?><br>
          <?php echo $app->user->info->city?>      
        </a>
      </td>
      <td><a href="<?php echo $app->job->link ? $app->job->link : $this->url('lang/jobs/view', array(), array('query' => array('id' => $app->job->id)), true) ?>"><?php echo $app->job->title?></a></td>
      <td><span class="ats-application-status <?php echo $app->status->name ?>"><?php echo $this->translate($app->status->name) ?></span></td>
      <td><?php echo $this->dateFormat($app->dateCreated, 'short', 'none') ?></td>
    </tr>
<?php endforeach ?>
</table>
<div class="ats-panel-foot">
<?php
echo $this->paginationControl($this->applications, 'Sliding', 'pagination-control', array('lang' => $this->params('lang'), 'route' => 'lang/applications-dashboard'));
?>
</div>
<?php if (!$this->isAjaxRequest): ?>
</div>
<?php endif ?>