<?php 
$this->headTitle($this->translate('Apply'));
$this->headscript()
        ->appendFile($this->basepath('Core/js/select2.min.js'))
        ->appendFile($this->basepath('Core/js/jquery.formcollection.js'));
$this->headLink()->appendStylesheet($this->basePath() . '/css/ats.css');
$this->headLink()->appendStylesheet($this->basePath() . '/css/ats.css');
$this->headLink()->appendStylesheet($this->basePath() . '/css/select2.css');
$this->headLink()->appendStylesheet($this->basePath() . '/css/select2-bootstrap.css');
$this->headscript()->appendScript('$(".alert").alert();');
?>
<?php $jobLink = $job->link ? $job->link : $this->url('lang/jobs/view', array(), array('query' => array('id' => $job->id)), true) ?>
<h1><?php echo $this->translate('Application')?>
<small>
<?php printf(
    $this->translate('for "%s"'), 
    '<a href="'.$jobLink.'" title="' . $this->translate('click to open the job ad') . '">' . $this->escapehtml(strip_tags($job->title)) . '</a>')?>
</small>
</h1>

<?php if (!$isApplicationSaved):
    $form->setAttributes(array(
        'action' => $this->url('lang/apply/submit', array(), true),
        'method' => 'post',
        'id' => 'application-form',
    ));
        
    echo $this->form($form, Core\Form\View\Helper\Form::LAYOUT_HORIZONTAL);
endif; ?>
 