<div class="row">
    <div class='v-center'>
        <div class="col-xs-6 col-xs-offset-3">
            <p class="text-right"><a href="<?php echo $this->url('lang/intern-register') ?>"><?php echo $this->translate('Need an account?') ?></a></p>
                <?php
                $this->loginForm->setAttributes(array(
                    'action' => $this->url('lang/intern-login', array(), array('query' => array_map('urlencode', $this->params()->fromQuery())), true),
                    'method' => 'post',
                    'id' => 'login-form',
                ));
                ?>
                <?php echo $this->form($this->loginForm); ?>

            <div class='clearfix'></div>
            <div class="row">    
                <div class="col-xs-12 text-center"><h5 class="text-center text-primary">Or you can also login using ...</h5></div>
            </div>
            <br /><br />
            <div class="row">
                <div class="col-xs-6">
                    <a class="btn btn-large btn-block btn-default" title="<?php echo sprintf($this->translate('Login with %s'), 'LinkedIn') ?>" href="<?php echo $this->url('auth-provider', array('provider' => 'linkedin'), array('query' => array('ref' => urlencode('/')))) ?>"><i class="ppt-icon ppt-icon-linkedin"></i> LinkedIn</a>
                </div>
                <div class="col-xs-6">
                    <a class="btn btn-large btn-block btn-default" title="<?php echo sprintf($this->translate('Login with %s'), 'Facebook') ?>" href="<?php echo $this->url('auth-provider', array('provider' => 'facebook'), array('query' => array('ref' => urlencode('/')))) ?>"><i class="ppt-icon ppt-icon-facebook"></i> Facebook</a>
                </div>
            </div>
        </div>
    </div>
</div>