<?php if (!$this->isAjaxRequest): ?>
<div class="panel panel-default pagination-container">
<?php endif ?>
<div class="panel-heading">
<?php echo $this->translate('List of jobs') ?>
</div>
<table class="table table-striped table-hover" id="jobs-list">
    <thead>
        <tr>
            <th><?php echo $this->translate('Details') ?></th>
            <?php if (!$this->acl()->isRole('user')): ?>  
                <th><?php echo $this->translate('Applications') ?></th>
                <th><?php echo $this->translate('Status') ?></th>
                <th><?php echo $this->translate('Action') ?></th>
            <?php else: ?>
                <th><?php echo $this->translate('Action') ?></th>
            <?php endif; ?>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($jobs as $job): ?>
            <tr>
                <td>
                    
                    <?php $href = $job->link ? $job->link : $this->url('lang/jobs/view', array(), array('query' => array('id' => $job->id)), true); ?>
                    <h2 class="table-data-title"><a href="<?php echo $href ?>"><?php echo strip_tags($job->title) ?></a></h2>
                    <p><em><?php echo $this->translate('Ref # ') ?><?php echo empty($job->reference) ? $job->applyId : $job->reference ?></em> |
                    <?php if ($this->auth('role') == 'recruiter'): ?>
                        (<?php echo $job->getUser()->getInfo()->getDisplayName() ?>) | 
                    <?php endif ?>                      
                    <?php echo $job->location ?> |
                    <?php if ($job->datePublishStart): echo $this->dateFormat($job->datePublishStart, 'short', 'none');
                    elseif ($job->dateCreated): echo $this->dateFormat($job->dateCreated, 'short', 'none');
                    endif
                    ?>
                    </p>
                    <p><?php echo $this->truncate($job->description, 300, ' <small><a href="'.$href.'">more</a></small>') ?></p>
                </td>
                <td>
                    <?php if (!$this->acl()->isRole('user')): ?>
                        <?php if ($job->applications->count() > 0): ?>
                            <a title="<?php echo $this->translate("total") ?>" href="<?php echo $this->url('lang/applications', array(), array('query' => 'job=' . $job->id), true) ?>">
                                <span class="badge"><?php echo $job->applications->count(); ?></span>
                            </a>
                        <?php endif; ?>
                        <?php if ($job->unreadApplications->count()): ?>       
                                            / 
                                    <a title="<?php echo $this->translate("unread") ?>" 
                                       href="<?php echo $this->url('lang/applications', array(), array('query' => 'job=' . $job->id . '&by=new'), true) ?>">
                                        <span class="badge"> <?php echo $job->unreadApplications->count() ?></span>
                                    </a>
                                <?php endif; ?>
                            <td>
                                <?php echo $job->status ?>
                            </td>
                            <td>
                            <?php if ($this->acl($job, 'edit') || $this->acl()->isRole('admin')): ?>
                                <div class="btn-group">
                                    <a href="<?php echo $this->url('lang/jobs/manage', array('action' => 'edit'), array('query' => array('id' => $job->id)), true) ?>" class="btn btn-default btn-xs"><span class="ppt-icon ppt-icon-edit"></span></a>
                                </div>
                            <?php endif ?>     
                            </td>
                    <?php else: ?>
                        <a class="btn btn-primary btn-xs" href="<?php
                           $url = $this->url('lang/apply/form', array('jobId' => $job->applyId, 'lang' => $this->params('lang')));
                           $query = http_build_query(array('subscriberUri' => $this->serverUrl() . '/subscriber/' . 1));
                           echo $url . '?' . $query;
                           ?>">
                        <?php echo $this->translate('Apply') ?>
                        </a>
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>
<div class="ats-panel-foot">    
<?php echo $this->paginationControl($jobs, 'Sliding', 'pagination-control', array('lang' => $this->params('lang'), 'route' => 'lang/jobs')) ?>
</div>
<?php if (!$this->isAjaxRequest): ?>
</div>
<?php endif ?>