<?php $this->headTitle($this->translate('Jobs'));
      $this->headScript()->appendFile($this->basepath('/Core/js/core.pagination.js'))?>

<h1><?php echo $this->translate('Jobs')?></h1>

<?php echo $this->flashMessenger()->render('default', array('alert', 'alert-success')) ?>

<nav class="navbar ats-toolbar" id="jobs-list-filter-wrapper">
<?php echo $this->form($this->filterForm)  ?>
</nav>
<div id="jobs-list-container" class="pagination-container">
<?php echo $this->render('jobs/index/index.ajax.phtml')?>
</div>

