<?php $this->headTitle()->append($this->escapeHtml($this->job->title))->append($this->translate('Jobs')) ?>

<h2><?php echo $this->job->title?><br><small><?php #echo $this->job->company ?><?php echo $this->job->location ?></small></h2>

<p><?php echo $this->translate('Online since') ?>: <?php echo $this->dateFormat($this->job->dateCreated, 'short') ?></p>

<hr />
<h3><?php echo $this->translate('Description') ?></h3>
<p><?php echo nl2br($job->description) ?></p>
<h3><?php echo nl2br('Duties/Responsibility') ?></h3>
<p><?php echo nl2br($job->responsibility) ?></p>
<h3><?php echo nl2br('Skills/Qualification') ?></h3>
<p><?php echo nl2br($job->qualification) ?></p>
<hr />
<!--<a href="<?php echo $this->url('lang/apply/form', array('jobId' => $job->applyId)); ?>" class="btn btn-primary pull-right"><?php echo $this->translate('Apply') ?></a>-->
